# Site settings
title: BitNeed
email: fabiodellagiustina1997@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Sérgio Nóbrega
  pic: sergio
  position: General Manager
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/sernobrega/

- name: Carlotta Tagliaro
  pic: carlotta
  position: Finance Responsible
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/carlotta-tagliaro-236384190/

- name: Luca Morgese
  pic: luca
  position: Technology Responsible
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/luca-morgese-8492aa188/

- name: Natalia Lopez
  pic: natalia
  position: Marketing Responsible
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/natalia-l%C3%B3pez-marin-23842117a/

- name: Fabio Della Giustina
  pic: fabio
  position: Technology Responsible
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/fabio-della-giustina/

- name: Giulia Brusadin
  pic: giulia
  position: Product Development Responsible
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/giulia-brusadin-48665517b/

- name: Riccardo Gorla
  pic: riccardo
  position: Product Development Responsible
  social:
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
